name: Events Demo 1
#on: [push, workflow_dispatch]
# we do not want all pushes to all branches to execute this workflow
# we do not want to deploy unless master branch pushed..
on:
  pull_request:
    #types: [opened, edited]
    types:
      - opened
      #- edited
      # which activity types trigger the pull_request
    branches:
      - main # main
      - master
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main # main
      - master
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
      # developer-1
    paths-ignore:
      - '.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."